<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecom_sku_generator"
 *
 * Auto generated by Extension Builder 2015-10-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SKU Generator',
	'description' => 'SKU Generator',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'Sebastian.Iffland@ecom-ex.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'typo3' => '6.2',
			'php' => '5.5',
			'ecom_toolbox' => '1.2.0',
			'powermail' => '',
			'ecom_config_code_generator' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);